feature/96: Added validation of README.md
exasol/project-keeper-maven-plugin pull request #149
Opened 2021-07-01 10:10 UTC by jakobbraun

Closes #96

2021-07-01 11:27 UTC, morazow requested changes

2021-07-01 11:27 UTC, morazow commented on src/main/java/com/exasol/projectkeeper/validators/ReadmeValidator.java
> +                "https://search.maven.org/artifact/com.exasol/project-keeper-maven-plugin" + this.artifactId);
This seems to be typo.
```suggestion
                "https://search.maven.org/artifact/com.exasol/" + this.artifactId);
```

2021-07-01 12:15 UTC, jakobbraun commented on src/main/java/com/exasol/projectkeeper/validators/AbstractFileValidator.java
> +     *
```suggestion
     *  Create a new file with a template content. 
     * <p>
     * The {@link AbstractFileValidator} calls this method when it applies the fix for a missing file.
     * </p>
```

2021-07-01 12:45 UTC, jakobbraun commented on src/main/java/com/exasol/projectkeeper/ProjectKeeperFixMojo.java
> +            log.warn("Could not auto-fix: " + unfixedFinding.getMessage());
yes. Added

2021-07-02 07:13 UTC, morazow commented on src/main/java/com/exasol/projectkeeper/validators/AbstractFileValidator.java
> +     * </p>
:+1:

2021-07-02 07:14 UTC, morazow approved these changes
Looks good!

2021-07-02 07:56 UTC, merged