#21 Added validation for doc/changes/changelog_X.X.X.md
exasol/project-keeper-maven-plugin pull request #23
Opened 2020-10-23 10:28 UTC by jakobbraun

Closes #21

2020-10-26 11:54 UTC, AnastasiiaSergienko requested changes

2020-10-27 07:25 UTC, jakobbraun commented on src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java
> +    public void validate(final FileTemplate template, final Consumer<ValidationFinding> findingConsumer) {
because java does not support package private for sub-packages. And I wanted to structure it further.

2020-10-27 07:27 UTC, jakobbraun commented on src/main/java/com/exasol/projectkeeper/ValidationFinding.java
> +        void fixError(Log log);
Yes, but I wanted to tell the users something when fixing.

2020-10-27 07:28 UTC, jakobbraun commented on src/main/java/com/exasol/projectkeeper/Validator.java
> +     * Flush the changes made by fixes.
It's the changes made by its fixes. The clean solution would be to write the file after each fix. But I don't want to write a single file 20 times if writing it once is enough.

2020-10-28 07:11 UTC, AnastasiiaSergienko commented
Please check the code smells sonar found

2020-10-28 07:16 UTC, AnastasiiaSergienko approved these changes
Looks good to me. Please, only check the Sonar findings

2020-10-28 11:10 UTC, merged