Refactor/247 version from source
exasol/project-keeper-maven-plugin pull request #248
Opened 2022-02-28 10:33 UTC by jakobbraun

Closes #247

2022-02-28 12:39 UTC, kaklakariada requested changes

2022-02-28 12:39 UTC, kaklakariada commented on project-keeper/src/main/java/com/exasol/projectkeeper/ProjectVersionDetector.java
> +                    .mitigation("Please specify a different source to read from or set an explicit version.")
```suggestion
                    .mitigation("Please specify a different source to read from or set an explicit version in your project-keeper config.")
```

2022-02-28 12:39 UTC, kaklakariada commented on project-keeper/src/main/java/com/exasol/projectkeeper/ProjectVersionDetector.java
> +                            "Please make sure that you defined a source with exactly the same path. There following sources are defined in the config: {{sources}}.",
```suggestion
                            "Please make sure that you defined a source with exactly the same path. The following sources are defined in the config: {{sources}}.",
```

2022-02-28 12:39 UTC, kaklakariada commented on project-keeper/src/main/java/com/exasol/projectkeeper/config/ProjectKeeperConfig.java
> +     * interface for classes that tell PK how to find out the overall project version.
```suggestion
     * Interface for classes that tell PK how to find out the overall project version.
```

2022-02-28 12:39 UTC, kaklakariada commented on project-keeper/src/main/java/com/exasol/projectkeeper/config/ProjectKeeperConfig.java
> +    public interface VersionProvider {
This name is misleading. From a `VersionProvider` i would expect a `get()` method that returns the version.
Maybe rename to `VersionConfig`?

2022-02-28 12:42 UTC, jakobbraun commented on .project-keeper.yml
> +      - udf_coverage
yes. It's called udf coverage but means: "Get coverage from a JVM that is run during tests." Here we start mvn in the tests

2022-03-01 09:42 UTC, kaklakariada approved these changes

2022-03-01 09:53 UTC, merged